name: microCMS Now Deploy
on:
  # push時の条件
  push:
    paths:
      - "gridsome-micro-cms-sample/**"
  # microCMSが更新されたときの条件
  repository_dispatch:
    types: [micro_cms_updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd gridsome-micro-cms-sample
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.MICROCMS_SAMPLE_NOW_ZEIT_TOKEN }}
          now-org-id: ${{ secrets.MICROCMS_SAMPLE_NOW_ORG_ID }}
          now-project-id: ${{ secrets.MICROCMS_SAMPLE_NOW_PROJECT_ID }}
